TOPDIR ?= ../..
include $(TOPDIR)/.config

$(WTEST)_ECMD_SRC += protocols/wtest/wtest_ecmd.c

##############################################################################
# generic fluff
#include $(TOPDIR)/scripts/rules.mk