/* Autogenerated File */
#define OUTPUT 0
#define INPUT 1
#define LOW 0
#define HIGH 1
const char named_pin_text22737[] PROGMEM = "p1";
const char named_pin_text3344[] PROGMEM = "p2";
const char named_pin_text21916[] PROGMEM = "p3";
const char named_pin_text9827[] PROGMEM = "p4";

const struct PinConfiguration portio_pincfg[] PROGMEM = {
    /*  port	pin	input	reverse? */
	{	0,	0,	OUTPUT,	HIGH,	named_pin_text22737 }, 	/* p1	*/ 
	{	0,	1,	OUTPUT,	HIGH,	named_pin_text3344 }, 	/* p2	*/ 
	{	0,	2,	OUTPUT,	HIGH,	named_pin_text21916 }, 	/* p3	*/ 
	{	0,	3,	OUTPUT,	HIGH,	named_pin_text9827 }, 	/* p4	*/ 

    /* mark the end of the list */
    { 255, 255, 255, 255, NULL}
};
