TOPDIR ?= ../..
include $(TOPDIR)/.config

$(WALDMANN)_ECMD_SRC += protocols/waldmann/waldmann_ecmd.c

##############################################################################
# generic fluff
#include $(TOPDIR)/scripts/rules.mk