TOPDIR ?= ../..
include $(TOPDIR)/.config

#$(WALDMANN_SUPPORT)_SRC += protocols/waldmann/waldmann.c
$(WALDMANN_SUPPORT)_ECMD_SRC += protocols/waldmann/waldmann_ecmd.c

##############################################################################
# generic fluff
#include $(TOPDIR)/scripts/rules.mk